-- MySQL Script generated by MySQL Workbench
-- 04/03/17 22:19:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZonaUrbana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZonaUrbana` (
  `NombreZona` VARCHAR(20) NOT NULL,
  `OdZona` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`NombreZona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda` (
  `calle` VARCHAR(40) NOT NULL,
  `numero` INT(4) NOT NULL,
  `tipo_vivienda` VARCHAR(1) NOT NULL,
  `codigo_postal` INT(5) NOT NULL,
  `metros` INT(5) NOT NULL,
  `od_vivienda` VARCHAR(45) NOT NULL,
  `ZonaUrbana_NombreZona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`calle`, `numero`),
  INDEX `fk_Vivienda_ZonaUrbana_idx` (`ZonaUrbana_NombreZona` ASC),
  CONSTRAINT `fk_Vivienda_ZonaUrbana`
    FOREIGN KEY (`ZonaUrbana_NombreZona`)
    REFERENCES `mydb`.`ZonaUrbana` (`NombreZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `dni` INT NOT NULL,
  `nombre_persona` VARCHAR(20) NOT NULL,
  `apellidos_persona` VARCHAR(40) NOT NULL,
  `od_persona` MEDIUMTEXT NULL,
  `Vivienda_calle` VARCHAR(40) NOT NULL,
  `Vivienda_numero` INT(4) NOT NULL,
  `Persona_dni_c` INT NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_Persona_Vivienda1_idx` (`Vivienda_calle` ASC, `Vivienda_numero` ASC),
  INDEX `fk_Persona_Persona1_idx` (`Persona_dni_c` ASC),
  CONSTRAINT `fk_Persona_Vivienda1`
    FOREIGN KEY (`Vivienda_calle` , `Vivienda_numero`)
    REFERENCES `mydb`.`Vivienda` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Persona1`
    FOREIGN KEY (`Persona_dni_c`)
    REFERENCES `mydb`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BloqueCasas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BloqueCasas` (
  `metros_b` INT(4) NULL,
  `od_bloque` MEDIUMTEXT NULL,
  `Vivienda_calle` VARCHAR(40) NOT NULL,
  `Vivienda_numero` INT(4) NOT NULL,
  INDEX `fk_BloqueCasas_Vivienda1_idx` (`Vivienda_calle` ASC, `Vivienda_numero` ASC),
  PRIMARY KEY (`Vivienda_calle`, `Vivienda_numero`),
  CONSTRAINT `fk_BloqueCasas_Vivienda1`
    FOREIGN KEY (`Vivienda_calle` , `Vivienda_numero`)
    REFERENCES `mydb`.`Vivienda` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `escalera` VARCHAR(1) NOT NULL,
  `planta` INT(2) NOT NULL,
  `puerta` VARCHAR(2) NOT NULL,
  `metros_p` INT(3) NULL,
  `od_piso` MEDIUMTEXT NULL,
  `BloqueCasas_Vivienda_calle` VARCHAR(40) NOT NULL,
  `BloqueCasas_Vivienda_numero` INT(4) NOT NULL,
  `Persona_dni_p` INT NOT NULL,
  PRIMARY KEY (`escalera`, `planta`, `puerta`, `BloqueCasas_Vivienda_calle`, `BloqueCasas_Vivienda_numero`),
  INDEX `fk_Piso_BloqueCasas1_idx` (`BloqueCasas_Vivienda_calle` ASC, `BloqueCasas_Vivienda_numero` ASC),
  INDEX `fk_Piso_Persona1_idx` (`Persona_dni_p` ASC),
  CONSTRAINT `fk_Piso_BloqueCasas1`
    FOREIGN KEY (`BloqueCasas_Vivienda_calle` , `BloqueCasas_Vivienda_numero`)
    REFERENCES `mydb`.`BloqueCasas` (`Vivienda_calle` , `Vivienda_numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Persona1`
    FOREIGN KEY (`Persona_dni_p`)
    REFERENCES `mydb`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HabitaPiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HabitaPiso` (
  `Persona_dni` INT NOT NULL,
  `Piso_escalera` VARCHAR(1) NOT NULL,
  `Piso_planta` INT(2) NOT NULL,
  `Piso_puerta` VARCHAR(2) NOT NULL,
  `Piso_BloqueCasas_Vivienda_calle` VARCHAR(40) NOT NULL,
  `Piso_BloqueCasas_Vivienda_numero` INT(4) NOT NULL,
  INDEX `fk_HabitaPiso_Persona1_idx` (`Persona_dni` ASC),
  INDEX `fk_HabitaPiso_Piso1_idx` (`Piso_escalera` ASC, `Piso_planta` ASC, `Piso_puerta` ASC, `Piso_BloqueCasas_Vivienda_calle` ASC, `Piso_BloqueCasas_Vivienda_numero` ASC),
  PRIMARY KEY (`Persona_dni`),
  CONSTRAINT `fk_HabitaPiso_Persona1`
    FOREIGN KEY (`Persona_dni`)
    REFERENCES `mydb`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HabitaPiso_Piso1`
    FOREIGN KEY (`Piso_escalera` , `Piso_planta` , `Piso_puerta` , `Piso_BloqueCasas_Vivienda_calle` , `Piso_BloqueCasas_Vivienda_numero`)
    REFERENCES `mydb`.`Piso` (`escalera` , `planta` , `puerta` , `BloqueCasas_Vivienda_calle` , `BloqueCasas_Vivienda_numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CasaParticular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CasaParticular` (
  `metros_c` INT(4) NULL,
  `od_casa` MEDIUMTEXT NULL,
  `Persona_dni_cp` INT NOT NULL,
  `Vivienda_calle` VARCHAR(40) NOT NULL,
  `Vivienda_numero` INT(4) NOT NULL,
  INDEX `fk_CasaParticular_Persona1_idx` (`Persona_dni_cp` ASC),
  INDEX `fk_CasaParticular_Vivienda1_idx` (`Vivienda_calle` ASC, `Vivienda_numero` ASC),
  PRIMARY KEY (`Vivienda_calle`, `Vivienda_numero`),
  CONSTRAINT `fk_CasaParticular_Persona1`
    FOREIGN KEY (`Persona_dni_cp`)
    REFERENCES `mydb`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasaParticular_Vivienda1`
    FOREIGN KEY (`Vivienda_calle` , `Vivienda_numero`)
    REFERENCES `mydb`.`Vivienda` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
