-- PARA VER LOS PRODUCTOS MAS VENDIDOS

SELECT COD_PRODUCTO, COUNT(*) AS CANTIDAD_VENDIDA
FROM TBL_PRODUCTO_X_FACTURA
GROUP BY COD_PRODUCTO
ORDER BY CANTIDAD_VENDIDA DESC;

-- PARA HACER UN CONTEO DE LOS PRODUCTOS X ALMACEN

SELECT B.NOMBRE_ALMACEN, C.NOMBRE_PRODUCTO, COUNT(*) CANTIDAD_ALMACENADA
FROM TBL_PRODUCTOS_X_ALMACEN A
LEFT JOIN TBL_ALMACEN B
ON (A.COD_ALMACEN = B.COD_ALMACEN)
LEFT JOIN TBL_PRODUCTO C
ON (A.COD_PRODUCTO = C.COD_PRODUCTO) 
GROUP BY B.NOMBRE_ALMACEN, C.NOMBRE_PRODUCTO
ORDER BY B.NOMBRE_ALMACEN;

-- PARA HACER UN CONTEO DE LOS PRODUCTOS POR LOCAL

SELECT B.NOMBRE_FARMACIA, C.NOMBRE_PRODUCTO, COUNT(*) CANTIDAD_ALMACENADA
FROM TBL_PRODUCTO_X_FARMACIA A
LEFT JOIN TBL_FARMACIA B
ON (A.COD_FARMACIA = B.COD_FARMACIA)
LEFT JOIN TBL_PRODUCTO C
ON (A.COD_PRODUCTO = C.COD_PRODUCTO) 
GROUP BY B.NOMBRE_FARMACIA, C.NOMBRE_PRODUCTO
ORDER BY B.NOMBRE_FARMACIA;

-- REPORTE DE VENTAS POR USUARIO, FECHA, FARMACIA, ZONA URBANA Y CIUDAD

-- Ventas por Usuario
SELECT B.NOMBRE_EMPLEADO as USUARIO, COUNT(*) AS CANTIDAD_DE_VENTAS 
FROM TBL_FACTURA A
LEFT JOIN TBL_EMPLEADO B
ON (A.COD_EMPLEADO = B.COD_EMPLEADO)
GROUP BY B.NOMBRE_EMPLEADO;

-- Ventas por fecha
SELECT FECHA_FACTURA AS FECHA, COUNT(*) AS CANTIDAD_VENTAS
FROM TBL_FACTURA
GROUP BY FECHA_FACTURA;

-- Ventas por farmacia
SELECT B.NOMBRE_FARMACIA AS FARMACIA, COUNT(*) AS CANTIDAD_VENTAS
FROM TBL_FACTURA A
LEFT JOIN TBL_FARMACIA B
ON (A.COD_FARMACIA = B.COD_FARMACIA)
GROUP BY B.NOMBRE_FARMACIA
ORDER BY B.NOMBRE_FARMACIA;

-- Ventas por Zona Urbana
SELECT G.NOMBRE_LOCALIDAD AS ZONA_URBANA, F.CANTIDAD_VENTAS
FROM
(
  SELECT C.COD_LOCALIDAD_PADRE, COUNT(*) AS CANTIDAD_VENTAS
  FROM TBL_FACTURA A
  LEFT JOIN TBL_FARMACIA B
  ON (A.COD_FARMACIA = B.COD_FARMACIA)
  LEFT JOIN TBL_LOCALIDADES C
  ON (B.COD_LOCALIDAD = C.COD_LOCALIDAD) 
  GROUP BY C.COD_LOCALIDAD_PADRE
) F
LEFT JOIN TBL_LOCALIDADES G
ON (F.COD_LOCALIDAD_PADRE = G.COD_LOCALIDAD);

-- Ventas por ciudad
SELECT G.NOMBRE_LOCALIDAD AS CIUDAD, F.CANTIDAD_VENTAS
FROM
(
  SELECT C.COD_LOCALIDAD, COUNT(*) AS CANTIDAD_VENTAS
  FROM TBL_FACTURA A
  LEFT JOIN TBL_FARMACIA B
  ON (A.COD_FARMACIA = B.COD_FARMACIA)
  LEFT JOIN TBL_LOCALIDADES C
  ON (B.COD_LOCALIDAD = C.COD_LOCALIDAD) 
  GROUP BY C.COD_LOCALIDAD
) F
LEFT JOIN TBL_LOCALIDADES G
ON (F.COD_LOCALIDAD = G.COD_LOCALIDAD);

-- VENTAS POR USUARIO FECHA ZONA URBANA Y CIUDAD (TODO JUNTO)
SELECT F.USUARIO, F.FECHA, G.NOMBRE_LOCALIDAD AS ZONA_URBANA, F.CIUDAD, COUNT(*) AS CANTIDAD_VENTAS
FROM
(
  SELECT B.NOMBRE_EMPLEADO AS USUARIO, A.FECHA_FACTURA AS FECHA, D.COD_LOCALIDAD_PADRE, D.NOMBRE_LOCALIDAD AS CIUDAD
  FROM TBL_FACTURA A
  LEFT JOIN TBL_EMPLEADO B
  ON (A.COD_EMPLEADO = B.COD_EMPLEADO)
  LEFT JOIN TBL_FARMACIA C
  ON (A.COD_FARMACIA = C.COD_FARMACIA)
  LEFT JOIN TBL_LOCALIDADES D
  ON (C.COD_LOCALIDAD = D.COD_LOCALIDAD)
) F
LEFT JOIN TBL_LOCALIDADES G
ON (F.COD_LOCALIDAD_PADRE = G.COD_LOCALIDAD) 
GROUP BY F.USUARIO, F.FECHA, G.NOMBRE_LOCALIDAD, F.CIUDAD;