SELECT CODIGO_USUARIO
  FROM (SELECT A.CODIGO_USUARIO
          FROM TBL_AMIGOS A
          JOIN TBL_ESTATUS_SOLICITUDES E
            ON E.CODIGO_ESTATUS = A.CODIGO_ESTATUS
           AND E.NOMBRE_ESTATUS = 'CONFIRMADA'
         GROUP BY A.CODIGO_USUARIO
         ORDER BY COUNT(*) DESC)
 WHERE ROWNUM < 2;
 
 SELECT CODIGO_USUARIO
  FROM (SELECT A.CODIGO_USUARIO
          FROM TBL_AMIGOS A
          JOIN TBL_ESTATUS_SOLICITUDES E
            ON E.CODIGO_ESTATUS = A.CODIGO_ESTATUS
           AND E.NOMBRE_ESTATUS = 'CONFIRMADA'
         GROUP BY A.CODIGO_USUARIO
         ORDER BY COUNT(*) ASC)
 WHERE ROWNUM < 15;
   
SELECT * 
FROM TBL_AMIGOS
WHERE CODIGO_ESTATUS = 1
ORDER BY CODIGO_USUARIO;

SELECT COUNT(DISTINCT CODIGO_USUARIO) AS NUMERO_DE_USUARIOS
FROM TBL_AMIGOS;
